import pricingModel from "../models/pricingModel.js";

export const pricingTierSetup = async () => {
    try {
        // Check if pricing tiers already exist
        const existingPricingTiers = await pricingModel.find({});

        if (existingPricingTiers.length === 0) {
            const pricingTiers = [
                {
                    name: "FREETIER",
                    title: "Free Tier",
                    description: "The free tier provides limited features and limited functionality.",
                    inspectionLimit: 1,
                    templateLimit: 1,
                    propertyLimit: 1,
                    monthlyPDFLimit: 10,
                    roomLimit: 5,
                    elementLimit: 5,
                    monthlyPrice: 0,
                    yearlyPrice: 0,
                    reportWatermark: "This Report is generated by Free Plan of Inspect Buddy",
                },
                {
                    name: "STANDARDTIER",
                    title: "Standard Tier",
                    description: "The standard tier provides basic features and limited functionality.",
                    inspectionLimit: 10,
                    templateLimit: 3,
                    propertyLimit: -999,
                    monthlyPDFLimit: 10,
                    roomLimit: 10,
                    elementLimit: 10,
                    monthlyPrice: 7,
                    yearlyPrice: 79,
                    reportWatermark: "",
                },
                {
                    name: "TOPTIER",
                    title: "Top Tier",
                    description: "The top tier provides advanced features and full functionality.",
                    inspectionLimit: -999,
                    templateLimit: -999,
                    propertyLimit: -999,
                    monthlyPDFLimit: -999,
                    roomLimit: 25,
                    elementLimit: 25,
                    monthlyPrice: 12,
                    yearlyPrice: 120,
                    reportWatermark: "",
                }
            ];

            // Use Promise.all to create both pricing tiers concurrently
            await Promise.all(
                pricingTiers.map(pricingTier => pricingModel.create(pricingTier))
            );

            console.log("Pricing tiers setup successfully");
        }
    } catch (err) {
        console.error(err);
        console.log("Failed to setup pricing tiers");
    }
};
